---
  header_logo_url: /public/images/logo.jpg
  header_logo_text: Ammonoidea of the World
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about

    - label: Help
      link: /help
