---
  header_logo_url: /images/logo.jpg
  header_logo_text: Ammonites of Gondwana
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about

    - label: Help
      link: /help
